### ISSUE TITLE
Getting Started Readme aio-cli-plugin-doc missing plugin?

### ISSUE THREAD

**Issue by ErinFinnegan** [adobe/gatsby-theme-aio#140]
# 📝 Feedback

In this section: [https://github.com/adobe/gatsby-theme-aio#using-the-adobe-io-cli](https://github.com/adobe/gatsby-theme-aio#using-the-adobe-io-cli)

> `aio discover -i`
> Select the @adobe/aio-cli-plugin-doc plugin by pressing the Spacebar and finally press Enter to install it.

The `aio-cli-plugin-doc` is no longer an option. Does that mean I've already installed it globally, or that it's no longer available (is it deprecated)?

## 🔦 Context

I need to open 12 new repos here: https://github.com/AdobeDocs - one for each Creative Cloud product. I need to onboard new authors, and am hoping for more clarity in the Getting Started doc.

## 🧢 Your Company/Team

Creative Cloud Developer Ecosystem - Developer Experience Team 🙋🏻‍♀️

**Comment by shazron** [comment]
@ErinFinnegan yes, if it's already installed, `aio discover -i` will not show it in the list. To confirm, just run `aio` and you should see the `doc` command
